services:
  ci:
    image: boids:ci
    build:
      dockerfile: .devcontainer/Dockerfile
      context: .
      target: base
    volumes:
      - ./build:/workspace/build:rw
      - ./scripts:/workspace/scripts:ro
      - ./src:/workspace/src:ro
      - ./test:/workspace/test:ro
      - ./CMakeLists.txt:/workspace/CMakeLists.txt:ro
    working_dir: /workspace
    command: bash -c "./scripts/build.sh && ./scripts/test.sh"

  prod:
    container_name: boids
    image: boids:prod
    build:
      dockerfile: .devcontainer/Dockerfile
      context: .
      target: prod
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-/dev/null}:/tmp/.Xauthority:ro
